FROM python:3.6-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV TERM xterm-256color

WORKDIR /prunetags

COPY . /prunetags/

RUN apk update
RUN apk add git gcc
RUN pip install --upgrade pip
RUN pip install pybuilder==0.11.17
RUN pyb clean
RUN pyb install_dependencies
RUN pyb -X

CMD echo 'DONE'
