---
name: 'app-service-configurable'
version: '4.0.0'
releaseName: 'odesa'
releaseStream: 'main'
lts: true
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: '08c35be361d297fe8f56dc197b9e919ce034e65a'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64