---
name: 'app-service-configurable'
version: '4.0.2'
releaseName: 'palau'
releaseStream: 'main'
lts: true
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: 'ab668cdbbecd7a9b1d8423e61e1b7cd8d327672a'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64