---
name: 'edgex-compose'
version: '4.0.2'
releaseName: 'palau'
releaseStream: 'palau'
lts: true
repo: 'https://github.com/edgexfoundry/edgex-compose.git'
commitId: '57c523c31e7725cbe11508ff0fa7de5736d4f051'
gitTag: true
dockerImages: false