---
name: 'edgex-compose'
version: '4.0.1'
releaseName: 'odessa'
releaseStream: 'odessa'
lts: true
repo: 'https://github.com/edgexfoundry/edgex-compose.git'
commitId: '5ed8d95a02329649a24ce79486b629bcdc8dad06'
gitTag: true
dockerImages: false