---
name: 'go-mod-configuration'
version: '4.0.2'
releaseName: 'odessa'
releaseStream: 'odessa'
lts: true
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: '963b1b797b37bb6552567a88a18a54456f429e87'
gitTag: true
dockerImages: false