---
name: 'go-mod-configuration'
version: '4.0.3'
releaseName: 'palau'
releaseStream: 'main'
lts: true
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: 'd45da4c960ab2abad19873850d21c36d19b42713'
gitTag: true
dockerImages: false